name: deploy-client-srv

on:
  push:
    branches:
      - master
    paths:
      - "skyway-client/**"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          echo "VITE_REACT_APP_API_KEY=${{ secrets.VITE_REACT_APP_API_KEY }}" >> skyway-client/.env
          echo "VITE_REACT_APP_AUTH_DOMAIN=${{ secrets.VITE_REACT_APP_AUTH_DOMAIN }}" >> skyway-client/.env
          echo "VITE_REACT_APP_PROJECTID=${{ secrets.VITE_REACT_APP_PROJECTID }}" >> skyway-client/.env      
          echo "VITE_REACT_APP_STORAGE_BUCKET=${{ secrets.VITE_REACT_APP_STORAGE_BUCKET }}" >> skyway-client/.env      
          echo "VITE_REACT_APP_MESSAGING_SENDER_ID=${{ secrets.VITE_REACT_APP_MESSAGING_SENDER_ID }}" >> skyway-client/.env      
          echo "VITE_REACT_APP_APP_ID=${{ secrets.VITE_REACT_APP_APP_ID }}" >> skyway-client/.env      
          echo "VITE_REACT_APP_MEASUREMENT=${{ secrets.VITE_REACT_APP_MEASUREMENT }}" >> skyway-client/.env      
          echo "VITE_REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.VITE_REACT_APP_GOOGLE_CLIENT_ID }}" >> skyway-client/.env      
      - run: cd skyway-client && docker build -t muhammedajmal/skyway-client-srv .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push muhammedajmal/skyway-client-srv
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save ${{secrets.CLUSTER_NAME}}
      - run: kubectl rollout restart deployment client-srv-deployment





