name: deploy-client-srv

on:
  push:
    branches:
      - master
    paths:
      - "skyway-client/**"
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd skyway-client && docker build -t muhammedajmal/skyway-client-srv .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push muhammedajmal/skyway-client-srv
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save skyway-k8s-cluster-digital-ocean
      - run: kubectl rollout restart client-srv-deployment





