name: deploy-user-srv

on:
  push:
    branches:
      - master
    paths:
      - "user-srv/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          echo "MONGO_URI=${{ secrets.USER_SRV_MONGO_URI }}" >> user-srv/.env
          echo "AWS_SECRETKEY=${{ secrets.AWS_SECRETKEY }}" >> user-srv/.env
          echo "AWS_ACCESSKEY=${{ secrets.AWS_ACCESSKEY }}" >> user-srv/.env
      - run: cd user-srv && docker build -t muhammedajmal/skyway-user-srv .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push muhammedajmal/skyway-user-srv
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save skway-2-k8s
      - run: kubectl rollout restart deployment user-srv-deployment





      
