name: deploy-chat-srv

on:
  push:
    branches:
      - master
    paths:
      - "chat-srv/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create .env file
        run: |
          echo "MONGO_URI=${{ secrets.chat_SRV_MONGO_URI }}" >> chat-srv/.env
          echo "VENTURE_SRV_TOKEN_SECRET_KEY=${{ secrets.JWT_SECRETKEY }}" >> chat-srv/.env
          echo "USER_SRV_TOKEN_SECRET_KEY=${{ secrets.JWT_USER_SECRET_KEY }}" >> chat-srv/.env
      - run: cd chat-srv && docker build -t muhammedajmal/skyway-chat-srv .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push muhammedajmal/skyway-chat-srv
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{secrets.DIGITALOCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save skway-2-k8s
      - run : kubectl rollout restart deployment chat-srv-deployment
