name: user-deploy

on:
  push:
    branches:
      - master  
    paths:
      - "user-srv/**"

jobs:
  build:
    runs-on: ubuntu:latest
    steps: 
      - uses: actions/checkout@v2
      - run: cd user-srv && docker build -t muhammedajmal/skyway-user-srv .
      - run : docker login -u $DOCKER_NAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push muhammedajmal/user-srv     
