name: test-user-srv

on:
  pull_request:
    paths:
      - "user-srv/**"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run : cd user-srv && npm install
