name: test-admin-srv

on:
  pull_request:
    paths:
      - "admin-srv/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd admin-srv && npm install
  
