name: test-client-srv

on:
  pull_request:
    paths:
      - "skyway-client/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd skyway-client && npm install
      
  
