name: test-chat-srv

on:
  pull_request:
    paths:
      - "chat-srv/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd chat-srv && npm install
  
